function imported = clean_import_log(filename)
% Auto-generated by MATLAB on 27-Dec-2023 14:00:44
% Adapted to multiple log files by Filippo Cerpelloni

%dataLines is not specified, define defaults
dataLines = [1, Inf];

%% Set up the Import Options and import the data
% Data log files have always the same structure, so no need to
% differentiate between sessions in this step
% Structure of log file:
% - timing 
% - type of event
% - description / action performed

% Nonetheless, we need session information for the trimming of data

opts = delimitedTextImportOptions("NumVariables", 3);
opts.DataLines = dataLines;
opts.Delimiter = "\t";
opts.VariableNames = ["Timing", "EVENT", "Description"];
opts.VariableTypes = ["double", "string", "string"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts = setvaropts(opts, "Description", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["EVENT", "Description"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Timing", "ThousandsSeparator", ",");

% Import the data
imported = readtable(filename, opts);

% Manipulate the table to get organized data
% trimmed = clean_trim_log(imported, session);

end